# Generated by Django 4.2.16 on 2026-05-21 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('dificultad', models.CharField(choices=[('FACIL', 'Facil'), ('MEDIO', 'Medio'), ('DIFICIL', 'Dificil')], default='FACIL', max_length=10, verbose_name='Dificultad')),
                ('puntos_recompensa', models.PositiveIntegerField(default=10, verbose_name='Puntos de recompensa')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mision',
                'verbose_name_plural': 'Misiones',
                'db_table': 'misiones',
                'ordering': ['nivel', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de aparicion')),
                ('puntos_requeridos', models.PositiveIntegerField(default=0, verbose_name='Puntos requeridos para desbloquear')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='niveles/', verbose_name='Imagen del nivel')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'db_table': 'niveles',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Enunciado de la pregunta')),
                ('tipo', models.CharField(choices=[('SELECCION_MULTIPLE', 'Seleccion múltiple'), ('VERDADERO_FALSO', 'Verdadero o Falso'), ('COMPLETAR', 'Completar')], default='SELECCION_MULTIPLE', max_length=30, verbose_name='Tipo de pregunta')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='preguntas/', verbose_name='Imagen de apoyo')),
                ('puntos', models.PositiveIntegerField(default=5, verbose_name='Puntos por respuesta correcta')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='game.mision', verbose_name='Mision')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'preguntas',
                'ordering': ['mision', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto de la respuesta')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Es correcta?')),
                ('retroalimentacion', models.TextField(blank=True, default='', verbose_name='Retroalimentacion')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='game.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'respuestas',
                'ordering': ['pregunta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField(verbose_name='¿Fue correcta?')),
                ('puntos_obtenidos', models.PositiveIntegerField(default=0, verbose_name='Puntos obtenidos')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de respuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_usuarios', to='game.pregunta', verbose_name='Pregunta')),
                ('respuesta_elegida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elegida_por_usuarios', to='game.respuesta', verbose_name='Respuesta elegida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_dadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Respuesta de usuario',
                'verbose_name_plural': 'Respuestas de usuarios',
                'db_table': 'respuestas_usuario',
                'ordering': ['-fecha_respuesta'],
            },
        ),
        migrations.AddField(
            model_name='mision',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misiones', to='game.nivel', verbose_name='Nivel'),
        ),
    ]
