# Generated by Django 4.2.16 on 2026-05-21 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveIntegerField(default=0, verbose_name='Posicion en el ranking')),
                ('puntos', models.PositiveIntegerField(default=0, verbose_name='Puntos totales')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nivel_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_en_nivel', to='game.nivel', verbose_name='Nivel actual')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Rankings',
                'db_table': 'ranking',
                'ordering': ['posicion'],
            },
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_preguntas_respondidas', models.PositiveIntegerField(default=0)),
                ('total_preguntas_correctas', models.PositiveIntegerField(default=0)),
                ('total_preguntas_incorrectas', models.PositiveIntegerField(default=0)),
                ('total_misiones_completadas', models.PositiveIntegerField(default=0)),
                ('total_niveles_completados', models.PositiveIntegerField(default=0)),
                ('total_puntos', models.PositiveIntegerField(default=0)),
                ('porcentaje_aciertos', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tiempo_total_minutos', models.PositiveIntegerField(default=0, verbose_name='Tiempo total en minutos')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadistica', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estadistica',
                'verbose_name_plural': 'Estadisticas',
                'db_table': 'estadisticas',
            },
        ),
        migrations.CreateModel(
            name='ProgresoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('NO_INICIADO', 'No iniciado'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADO', 'Completado')], default='NO_INICIADO', max_length=20, verbose_name='Estado')),
                ('porcentaje_completado', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Porcentaje completado')),
                ('puntos_ganados', models.PositiveIntegerField(default=0, verbose_name='Puntos ganados en esta mision')),
                ('intentos', models.PositiveIntegerField(default=0, verbose_name='Numero de intentos')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='Última actividad')),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_usuarios', to='game.mision', verbose_name='Mision')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Progreso de usuario',
                'verbose_name_plural': 'Progresos de usuarios',
                'db_table': 'progreso_usuario',
                'ordering': ['-ultima_actividad'],
                'unique_together': {('usuario', 'mision')},
            },
        ),
    ]
