# Generated by Django 4.2.16 on 2026-05-21 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Nombre de usuario')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('codigo_universitario', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Codigo universitario')),
                ('carrera', models.CharField(blank=True, default='', max_length=200, verbose_name='Carrera')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante')], default='ESTUDIANTE', max_length=20, verbose_name='Rol')),
                ('puntos_totales', models.PositiveIntegerField(default=0, verbose_name='Puntos totales')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='insignias/', verbose_name='Icono')),
                ('puntos_requeridos', models.PositiveIntegerField(default=0, verbose_name='Puntos requeridos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insignia',
                'verbose_name_plural': 'Insignias',
                'db_table': 'insignias',
                'ordering': ['puntos_requeridos'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioInsignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateTimeField(auto_now_add=True)),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_con_insignia', to='users.insignia', verbose_name='Insignia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias_obtenidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Insignia de usuario',
                'verbose_name_plural': 'Insignias de usuarios',
                'db_table': 'usuario_insignias',
                'ordering': ['-fecha_obtenida'],
                'unique_together': {('usuario', 'insignia')},
            },
        ),
    ]
